version: '3'

services:
  lager-neo4j:
    image: neo4j:4.4.4-community
    environment:
      NEO4J_AUTH: neo4j/PASSWORD
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ./data/neo4j:/data
  lager-nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./containers/nginx/config:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - lager-auth
  lager-auth:
    build:
      context: ./backend
      dockerfile: ${PWD:-..}/containers/auth.dockerfile
    volumes:
      - ./backend/dist:/lager/dist
      - ./backend/config.yml:/lager/config.yml
    depends_on:
      - lager-neo4j
